# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1794da060c3301343f7652e49a844c2ad772a6778c34d8207ff57b725e3bad236b8aaaabaa022428c45a6b53cc58e6a084bcb7b4ade57788cf0ea8cffe6eb79

test:
  secret_key_base: cb77350420a153f22132f698b3e1cc38cfa8dcd6c4f507e037666f7a05c47ea41719c693a052ef7299ca69c7834b82f9bc47e9ccb88f4a6a14e8078b022068d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
